# -*- coding: utf-8 -*-
"""The 35 Tier 2 countries the PrismHR global guides never covered.
Every bullet here is written from a public source and carries it. Nothing is
recalled and left unsourced: where a headline rate would misprice the country
(nationals-only schemes, uncapped funds, mandated extra months) the bullet says so.
"""
import json, io, os

PWC = "PwC Worldwide Tax Summaries"
TE = "Trading Economics country tables"
WIKI = "Wikipedia, minimum annual leave and public holidays by country"

# label order the sheet renders in
ORDER = ["Currency","VAT","Payroll cycle","Minimum wage","Working hours","Overtime",
         "Social security","Healthcare","Retirement","Paid time off","Public holidays",
         "Maternity leave","Sick leave","Probation","Notice period","Severance"]

N = {}

N["Vietnam"] = {
 "Currency": ("Vietnamese Dong (VND).", "ISO 4217"),
 "VAT": ("10% standard, with a temporary 2-point cut running through December 2026, and 0% or 5% on specified goods.", PWC),
 "Payroll cycle": ("Monthly. Wages are paid in Vietnamese Dong; foreign-currency salaries are converted for payroll.", "Vietnam Labour Code 2019, art. 95"),
 "Minimum wage": ("Set by region, not nationally: the top regional floor is 5,310,000 VND a month, and each of the four regions carries its own figure.", TE),
 "Working hours": ("48 hours a week is the legal norm, 8 hours a day.", "Vietnam Labour Code 2019, art. 105"),
 "Overtime": ("Capped at 12 hours in a day, 40 hours in a month and 200 hours in a year — 300 in named sectors.", "Vietnam Labour Code 2019, art. 107"),
 "Social security": ("Employer 17.5% social insurance, 3% health insurance and 1% unemployment insurance, each on a capped wage. Unemployment insurance covers Vietnamese nationals only.", PWC),
 "Healthcare": ("Health insurance is part of the statutory package: 3% employer, 1.5% employee, capped at 20 times the reference level.", PWC),
 "Retirement": ("Retirement runs through the state social insurance fund; the 17.5% employer contribution funds it. There is no separate mandatory private plan.", PWC),
 "Paid time off": ("12 working days a year after 12 months of service, more for hazardous work, plus one extra day for every five years with the same employer.", "Vietnam Labour Code 2019, art. 113"),
 "Public holidays": ("11 paid public holidays, with the Tet cluster taking five of them in one run.", "Vietnam Labour Code 2019, art. 112"),
 "Maternity leave": ("Six months, paid by the social insurance fund rather than the employer.", "Vietnam Social Insurance Law"),
 "Sick leave": ("Up to 30 days a year paid by social insurance for ordinary illness, longer for listed serious conditions.", "Vietnam Social Insurance Law"),
 "Probation": ("Up to 180 days for an enterprise manager, 60 days for a role needing a college degree, 30 days for a technical or skilled role, 6 working days for everything else.", "Vietnam Labour Code 2019, art. 25"),
 "Notice period": ("45 days on an indefinite contract, 30 days on a fixed contract of 12 to 36 months, 3 working days on a contract under 12 months.", "Vietnam Labour Code 2019, art. 35-36"),
 "Severance": ("Half a month's salary for every year of service, for anyone with at least 12 months of regular work, less the period covered by unemployment insurance.", "Vietnam Labour Code 2019, art. 46"),
}

N["Saudi Arabia"] = {
 "Currency": ("Saudi Riyal (SAR), pegged to the US dollar.", "ISO 4217"),
 "VAT": ("15%.", TE),
 "Payroll cycle": ("Monthly, and wages must run through the Mudad wage protection system for the payment to count as made.", "Saudi Ministry of Human Resources, wage protection rules"),
 "Minimum wage": ("No general statutory minimum for expatriates. A Saudi national must be paid at least 4,000 SAR a month to count as a full head toward the Saudization quota.", "Saudi Nitaqat program rules"),
 "Working hours": ("48 hours a week, dropping to 36 during Ramadan for Muslim employees.", "Saudi Labour Law, art. 98"),
 "Overtime": ("Paid at 150% of the hourly wage.", "Saudi Labour Law, art. 107"),
 "Social security": ("GOSI splits by nationality: 2% of salary, employer only, for an expatriate — occupational hazard cover alone. For a Saudi national it is 21.5% in total, 11.75% of it the employer's, on a wage capped at 45,000 SAR.", PWC),
 "Healthcare": ("Private medical cover is compulsory for every employee and their dependants; the employer buys and pays for the policy, and a residence permit will not renew without it.", "Saudi Cooperative Health Insurance Law"),
 "Retirement": ("The GOSI pension branch covers Saudi nationals only. An expatriate accrues no pension and is paid an end-of-service award instead.", PWC),
 "Paid time off": ("21 days a year, rising to 30 days once an employee has five continuous years with the same employer.", "Saudi Labour Law, art. 109"),
 "Public holidays": ("Eid al-Fitr, Eid al-Adha, Founding Day and National Day; the Eid dates move with the lunar calendar and are confirmed only days ahead.", "Saudi Labour Law, art. 112"),
 "Maternity leave": ("12 weeks at full pay, six of which must be taken after the birth.", "Saudi Labour Law, art. 151"),
 "Sick leave": ("Up to 120 days a year: full pay for the first 30, three quarters for the next 60, unpaid for the last 30.", "Saudi Labour Law, art. 117"),
 "Probation": ("Up to 90 days, extendable in writing to 180 in total. No end-of-service award is owed on a termination inside it.", "Saudi Labour Law, art. 53"),
 "Notice period": ("60 days on an indefinite contract, 30 days on a fixed one, unless the contract says more.", "Saudi Labour Law, art. 75"),
 "Severance": ("End-of-service award: half a month's wage for each of the first five years, a full month's wage for every year after that.", "Saudi Labour Law, art. 84"),
}

N["Norway"] = {
 "Currency": ("Norwegian Krone (NOK).", "ISO 4217"),
 "VAT": ("25% standard, 15% on groceries, 12% on transport and accommodation.", PWC),
 "Payroll cycle": ("Monthly.", "Norwegian Working Environment Act"),
 "Minimum wage": ("No statutory national minimum. Pay floors are set by collective agreement, and in construction, cleaning, hospitality and several other sectors those floors are declared universally binding on every employer in the sector.", "Norwegian Tariff Board, general application regulations"),
 "Working hours": ("9 hours a day and 40 hours a week is the legal ceiling; most collective agreements set 37.5.", "Norwegian Working Environment Act, ch. 10"),
 "Overtime": ("At least a 40% premium on top of the hourly rate, and overtime is capped by day, week and year.", "Norwegian Working Environment Act, ch. 10"),
 "Social security": ("Employer national insurance is 14.1%, with lower rates in designated sparsely populated areas.", PWC),
 "Healthcare": ("Covered by national insurance. There is no separate employer premium.", PWC),
 "Retirement": ("Occupational pension is compulsory from the first employee: at least 2% of salary above the national insurance base amount, paid into a registered scheme.", "Norwegian Mandatory Occupational Pension Act (OTP)"),
 "Paid time off": ("25 working days under the Holiday Act, taken as a six-day week, and holiday pay is a separate 10.2% of the prior year's earnings — 12.5% for an employee over 60.", "Norwegian Holiday Act (Ferieloven)"),
 "Public holidays": ("10 paid public holidays.", WIKI),
 "Maternity leave": ("Parental leave runs 49 weeks at full pay or 59 weeks at 80%, paid by the state, with weeks reserved to each parent.", "Norwegian National Insurance Act"),
 "Sick leave": ("The employer pays full salary for the first 16 calendar days of every absence; the state takes over after that.", "Norwegian National Insurance Act"),
 "Probation": ("Up to six months, with a 14-day notice period inside it.", "Norwegian Working Environment Act, §15-6"),
 "Notice period": ("One month as a minimum, stretching to six months for a long-serving older employee.", "Norwegian Working Environment Act, §15-3"),
 "Severance": ("No statutory severance. Dismissal must be objectively justified, and an employee who disputes it can demand to stay in the job on full pay while the case runs.", "Norwegian Working Environment Act, §15-11"),
}

N["Hong Kong"] = {
 "Currency": ("Hong Kong Dollar (HKD), pegged to the US dollar.", "ISO 4217"),
 "VAT": ("None. Hong Kong has no VAT, GST or sales tax.", PWC),
 "Payroll cycle": ("Monthly, and wages are due within seven days of the end of the wage period.", "Employment Ordinance (Cap. 57), s. 23"),
 "Minimum wage": ("43.10 HKD an hour.", TE),
 "Working hours": ("No statutory limit on working hours for most employees.", "Employment Ordinance (Cap. 57)"),
 "Overtime": ("No statutory overtime premium. What is paid is whatever the contract says.", "Employment Ordinance (Cap. 57)"),
 "Social security": ("The Mandatory Provident Fund: 5% employer and 5% employee, capped at 30,000 HKD of monthly income. An employee earning under 7,100 HKD a month contributes nothing, but the employer still pays its 5%.", PWC),
 "Healthcare": ("No mandatory employer medical cover; the public system carries it. Private cover is a market expectation rather than a rule.", "Hong Kong Labour Department"),
 "Retirement": ("The MPF is the retirement scheme. Contributions vest immediately and the account follows the employee.", "Mandatory Provident Fund Schemes Ordinance"),
 "Paid time off": ("7 days a year after 12 months of service, climbing one day a year to 14 after nine years.", "Employment Ordinance (Cap. 57), s. 41AA"),
 "Public holidays": ("15 statutory holidays in 2026, on a legislated path to 17 by 2030.", "Hong Kong Labour Department, statutory holidays 2026"),
 "Maternity leave": ("14 weeks, paid at four fifths of average daily wages.", "Employment Ordinance (Cap. 57), s. 12"),
 "Sick leave": ("Two paid sick days accrue per month in the first year and four a month after that, paid at four fifths of average daily wages once 4 days are accumulated.", "Employment Ordinance (Cap. 57), s. 33"),
 "Probation": ("Commonly three months. Inside the first month either side can walk with no notice.", "Employment Ordinance (Cap. 57), s. 6"),
 "Notice period": ("One month after probation, unless the contract sets more.", "Employment Ordinance (Cap. 57), s. 6"),
 "Severance": ("Two thirds of a month's wages per year of service on redundancy, on a wage capped at 22,500 HKD and a total capped at 390,000 HKD. Long service payment uses the same formula for a non-redundancy exit after five years.", "Employment Ordinance (Cap. 57), s. 31G-31V"),
}

N["Taiwan"] = {
 "Currency": ("New Taiwan Dollar (TWD).", "ISO 4217"),
 "VAT": ("5% business tax; 2% to 5% gross business receipts tax in financial and small-business sectors.", PWC),
 "Payroll cycle": ("Monthly.", "Labor Standards Act, art. 23"),
 "Minimum wage": ("29,500 TWD a month.", TE),
 "Working hours": ("8 hours a day and 40 hours a week, and no more than 12 hours in a single day counting overtime.", "Labor Standards Act, art. 30"),
 "Overtime": ("Paid at a rising premium by hour band, and capped at 46 hours a month.", "Labor Standards Act, art. 24 and 32"),
 "Social security": ("Employer carries roughly 70% of labor insurance (about 8% of insured salary), 60% of national health insurance (about 4.8%), and a separate 6% labor pension. Total employer load runs 15% to 20% of insured salary.", "Taiwan Bureau of Labor Insurance and National Health Insurance Administration rate schedules"),
 "Healthcare": ("National Health Insurance is compulsory, and a further 2.11% supplementary premium falls on bonuses above four times the monthly insured salary — the employer matches it.", PWC),
 "Retirement": ("At least 6% of monthly wages into the employee's own portable pension account under the Labor Pension Act. Foreign nationals are outside the labor pension program.", PWC),
 "Paid time off": ("Tied to seniority: 3 days at six months, 7 at one year, then climbing to 30 days after ten years.", "Labor Standards Act, art. 38"),
 "Public holidays": ("12 to 13 paid public holidays, with the Lunar New Year cluster the longest run.", "Taiwan Ministry of the Interior holiday schedule"),
 "Maternity leave": ("8 weeks at full pay for an employee with at least six months of service, half pay below that.", "Labor Standards Act, art. 50"),
 "Sick leave": ("Up to 30 days a year of ordinary sick leave at half pay, and up to a year of hospitalized sick leave.", "Taiwan Regulations on Leave-Taking of Workers"),
 "Probation": ("Not set in statute. Three months is the market norm and can be extended once by agreement.", "Taiwan Ministry of Labor guidance"),
 "Notice period": ("10 days from three months to a year of service, 20 days from one to three years, 30 days beyond three.", "Labor Standards Act, art. 16"),
 "Severance": ("Half a month's average pay per year of service under the current pension system, capped at six months' pay.", "Labor Pension Act, art. 12"),
}

N["Nigeria"] = {
 "Currency": ("Nigerian Naira (NGN).", "ISO 4217"),
 "VAT": ("7.5%.", PWC),
 "Payroll cycle": ("Monthly.", "Nigeria Labour Act"),
 "Minimum wage": ("70,000 NGN a month.", TE),
 "Working hours": ("Set by agreement rather than a single statutory week; a rest day every seven days and a break every six hours are mandatory.", "Nigeria Labour Act, s. 13"),
 "Overtime": ("No statutory premium. Overtime pay is whatever the contract or collective agreement sets.", "Nigeria Labour Act"),
 "Social security": ("Pension is the main employer charge: at least 10% employer and 8% employee, mandatory once the employer has 15 or more employees. Employee compensation runs a further 1% of payroll to the NSITF.", PWC),
 "Healthcare": ("National Health Insurance Authority registration is compulsory for employers, and most companies buy an HMO plan on top.", "National Health Insurance Authority Act 2022"),
 "Retirement": ("Contributory Pension Scheme. The employer may elect to carry the whole 20% instead of splitting it.", PWC),
 "Paid time off": ("Six working days a year under the Act after twelve months of service. Private employers commonly write 15 to 20 days into the contract because the statutory floor is not competitive.", "Nigeria Labour Act, s. 18"),
 "Public holidays": ("11 to 13 paid public holidays, with the Islamic dates confirmed only days ahead.", "Nigeria Public Holidays Act"),
 "Maternity leave": ("12 weeks at not less than 50% of pay, and the employee needs six months of service to qualify.", "Nigeria Labour Act, s. 54"),
 "Sick leave": ("Up to 12 paid days a year on a medical certificate.", "Nigeria Labour Act, s. 16"),
 "Probation": ("Not set in statute. Three to six months is the market norm.", "Nigeria Labour Act"),
 "Notice period": ("One week after three months of service, one month after a year, and longer by contract; pay in lieu is allowed.", "Nigeria Labour Act, s. 11"),
 "Severance": ("No statutory severance. What is owed comes from the contract, the staff handbook or a collective agreement, and the National Industrial Court enforces those terms.", "Nigeria Labour Act; National Industrial Court practice"),
}

N["Pakistan"] = {
 "Currency": ("Pakistani Rupee (PKR).", "ISO 4217"),
 "VAT": ("18% sales tax on goods; the provinces levy their own rates on services.", PWC),
 "Payroll cycle": ("Monthly.", "Payment of Wages Act 1936"),
 "Minimum wage": ("40,000 PKR a month, and each province sets its own figure.", TE),
 "Working hours": ("48 hours a week, up to 9 hours a day.", "Factories Act 1934"),
 "Overtime": ("Paid at double the ordinary rate.", "Factories Act 1934, s. 47"),
 "Social security": ("Employer pays 5% to the Employees Old-Age Benefits Institution on a capped wage, plus a provincial social security contribution — around 6% in Punjab and Sindh — on wages below the provincial threshold.", "EOBI Act 1976; provincial ESSI ordinances"),
 "Healthcare": ("Medical cover comes through provincial social security institutions for employees under the wage threshold; above it, private cover is a contract term.", "Provincial ESSI ordinances"),
 "Retirement": ("EOBI pension, plus gratuity or a provident fund under the standing orders.", "EOBI Act 1976"),
 "Paid time off": ("14 consecutive days a year after twelve months of service, plus 10 casual days.", "Factories Act 1934, s. 49B"),
 "Public holidays": ("Around 15 paid public holidays, several of them lunar and confirmed days ahead.", WIKI),
 "Maternity leave": ("180 days at full pay for a first birth, 120 for a second, 90 for a third under the federal Act; provinces vary.", "Maternity and Paternity Leave Act 2020"),
 "Sick leave": ("8 days a year at full pay on a medical certificate, plus longer paid sickness under the standing orders.", "West Pakistan Standing Orders Ordinance 1968"),
 "Probation": ("Three months under the standing orders, extendable to a further three.", "West Pakistan Standing Orders Ordinance 1968"),
 "Notice period": ("One month, or a month's wages in lieu.", "West Pakistan Standing Orders Ordinance 1968"),
 "Severance": ("Gratuity of 30 days' wages for every year of service once an employee has completed a year, unless a provident fund replaces it.", "West Pakistan Standing Orders Ordinance 1968"),
}

N["Ukraine"] = {
 "Currency": ("Ukrainian Hryvnia (UAH).", "ISO 4217"),
 "VAT": ("20% standard, with 14%, 7% and 0% bands.", PWC),
 "Payroll cycle": ("Twice a month is mandatory, with no more than sixteen days between the two payments.", "Ukraine Labour Code, art. 115"),
 "Minimum wage": ("8,647 UAH a month.", TE),
 "Working hours": ("40 hours a week.", "Ukraine Labour Code, art. 50"),
 "Overtime": ("Paid at double time, capped at 4 hours over two consecutive days and 120 hours a year.", "Ukraine Labour Code, art. 62 and 106"),
 "Social security": ("Unified social contribution of 22%, employer only, on a base capped at fifteen times the minimum wage — 129,705 UAH a month in 2026.", PWC),
 "Healthcare": ("No employer health premium; the state system carries it. Private cover is a market benefit.", PWC),
 "Retirement": ("Funded out of the 22% unified social contribution.", PWC),
 "Paid time off": ("24 calendar days a year, available after six continuous months.", "Ukraine Law on Leave, art. 6"),
 "Public holidays": ("11 paid public holidays.", "Ukraine Labour Code, art. 73"),
 "Maternity leave": ("126 calendar days — 70 before and 56 after the birth — paid by the social insurance fund.", "Ukraine Law on Compulsory State Social Insurance"),
 "Sick leave": ("The employer pays the first five days in full; the social insurance fund pays from day six at a rate set by length of insured service.", "Ukraine Law on Compulsory State Social Insurance"),
 "Probation": ("Up to three months, or six for a role requiring it.", "Ukraine Labour Code, art. 27"),
 "Notice period": ("Two months for a redundancy, and martial-law rules let an employer change terms on the same two months' notice without consent.", "Ukraine Labour Code, art. 49-2; martial-law employment rules"),
 "Severance": ("At least one month's average pay on redundancy, and at least two months where the employee leaves for military conscription.", "Ukraine Labour Code, art. 44"),
}

N["Bangladesh"] = {
 "Currency": ("Bangladeshi Taka (BDT).", "ISO 4217"),
 "VAT": ("15%.", TE),
 "Payroll cycle": ("Monthly, due within seven working days of the end of the wage period.", "Bangladesh Labour Act 2006, s. 123"),
 "Minimum wage": ("12,500 BDT a month; sector wage boards set higher floors, notably in garments.", TE),
 "Working hours": ("8 hours a day and 48 hours a week, stretching to 10 hours a day with overtime.", "Bangladesh Labour Act 2006, s. 100-102"),
 "Overtime": ("Paid at double the ordinary rate.", "Bangladesh Labour Act 2006, s. 108"),
 "Social security": ("No national social security scheme. Instead, a company above the capital threshold must pay 5% of net profit into the Workers' Profit Participation Fund each year, split 80:10:10 between the participation fund, the welfare fund and the national workers' welfare foundation.", "Bangladesh Labour Act 2006, s. 232-234"),
 "Healthcare": ("No mandatory employer health scheme. Larger establishments must run on-site medical facilities.", "Bangladesh Labour Act 2006"),
 "Retirement": ("A provident fund becomes compulsory only when three quarters of the workforce demand one in writing. Gratuity carries the rest.", "Bangladesh Labour Act 2006, s. 264"),
 "Paid time off": ("One day of earned leave for every 18 days worked, so roughly 10 to 20 days depending on attendance, plus 10 casual days.", "Bangladesh Labour Act 2006, s. 117"),
 "Public holidays": ("11 paid festival holidays.", "Bangladesh Labour Act 2006, s. 118"),
 "Maternity leave": ("120 days at full pay, and the employee may take the whole block before or after the birth.", "Bangladesh Labour Act (Amendment) 2023"),
 "Sick leave": ("14 days a year at full pay on a medical certificate.", "Bangladesh Labour Act 2006, s. 116"),
 "Probation": ("Six months for a clerical role, three months for everyone else.", "Bangladesh Labour Act 2006, s. 4"),
 "Notice period": ("120 days for a monthly-paid permanent worker, 60 days for others.", "Bangladesh Labour Act 2006, s. 26"),
 "Severance": ("30 days' wages per year of service, rising to 45 days per year after ten years.", "Bangladesh Labour Act 2006, s. 27"),
}

N["Morocco"] = {
 "Currency": ("Moroccan Dirham (MAD).", "ISO 4217"),
 "VAT": ("20% standard, with 10% and 0% bands.", PWC),
 "Payroll cycle": ("Monthly.", "Morocco Labour Code (Law 65-99)"),
 "Minimum wage": ("3,423 MAD a month in industry and services; agriculture carries its own lower floor.", TE),
 "Working hours": ("44 hours a week, up to 10 hours in a day.", "Morocco Labour Code, art. 184"),
 "Overtime": ("25% premium by day and 50% by night, rising to 50% and 100% on a rest day or holiday.", "Morocco Labour Code, art. 201"),
 "Social security": ("CNSS employer total is about 21.09% of gross: 6.40% family allocation with no ceiling, 8.98% social allocation capped at 6,000 MAD, 1.60% professional training, and 4.11% mandatory medical care.", PWC),
 "Healthcare": ("Mandatory medical care (AMO) through CNSS: 4.11% employer, 2.26% employee, uncapped.", PWC),
 "Retirement": ("Long-term benefits sit inside the capped 8.98% social allocation; supplementary pension through CIMR is common but voluntary.", PWC),
 "Paid time off": ("18 working days a year, accruing at 1.5 days a month after six months of service, plus 1.5 extra days for every five years of seniority.", "Morocco Labour Code, art. 231"),
 "Public holidays": ("13 paid public holidays.", WIKI),
 "Maternity leave": ("14 weeks at full pay, seven before and seven after the birth, paid by CNSS against a contribution record.", "Morocco Labour Code, art. 152"),
 "Sick leave": ("Paid by CNSS from the fourth day, subject to a contribution record.", "Morocco Social Security Code"),
 "Probation": ("Three months for a manager, a month and a half for an employee, fifteen days for a worker — each renewable once.", "Morocco Labour Code, art. 14"),
 "Notice period": ("One to three months, set by category and length of service.", "Morocco Labour Code, art. 43"),
 "Severance": ("Dismissal indemnity is priced in hours: 96 hours of salary per year for the first five years, 144 for the next five, 192 for the next five, 240 for every year beyond fifteen.", "Morocco Labour Code, art. 53"),
}

N["Sri Lanka"] = {
 "Currency": ("Sri Lankan Rupee (LKR).", "ISO 4217"),
 "VAT": ("18%.", TE),
 "Payroll cycle": ("Monthly.", "Shop and Office Employees Act 1954"),
 "Minimum wage": ("30,000 LKR a month.", TE),
 "Working hours": ("8 hours a day and 45 hours a week, excluding the one-hour break.", "Shop and Office Employees Act 1954"),
 "Overtime": ("Paid at one and a half times the hourly rate, capped at 12 hours a week.", "Shop and Office Employees Act 1954"),
 "Social security": ("Employer 12% to the Employees' Provident Fund and 3% to the Employees' Trust Fund, on top of the employee's own 8% — 15% of gross from the employer before anything else.", "EPF Act 1958; ETF Act 1980"),
 "Healthcare": ("No mandatory employer health scheme; the public system carries it.", "Sri Lanka Ministry of Health"),
 "Retirement": ("EPF and ETF are the retirement vehicles, plus gratuity for anyone with five years of service.", "EPF Act 1958; Payment of Gratuity Act 1983"),
 "Paid time off": ("14 days a year from the third calendar year of employment, rising to 21 days after five years.", "Shop and Office Employees Act 1954"),
 "Public holidays": ("Around 9 statutory paid holidays plus the monthly full-moon Poya days, which land on a lunar cycle rather than fixed dates.", "Shop and Office Employees Act 1954"),
 "Maternity leave": ("12 weeks at full pay for the first two children, 6 weeks after that.", "Maternity Benefits Ordinance"),
 "Sick leave": ("7 days of casual leave a year, with sick leave beyond that a matter of contract or practice.", "Shop and Office Employees Act 1954"),
 "Probation": ("Six months is the norm, extendable to twelve by agreement.", "Sri Lanka Department of Labour guidance"),
 "Notice period": ("One month by custom and contract; there is no single statutory figure.", "Sri Lanka Department of Labour guidance"),
 "Severance": ("Under the Termination of Employment of Workmen Act, an employer with 15 or more employees cannot dismiss a worker of one year's service without the worker's written consent or the Commissioner of Labour's prior approval, and the Commissioner sets the compensation.", "Termination of Employment of Workmen Act 1971"),
}

N["Ghana"] = {
 "Currency": ("Ghanaian Cedi (GHS).", "ISO 4217"),
 "VAT": ("15% VAT, and three levies ride on top — 2.5% health insurance, 2.5% education trust fund and 2.5% COVID recovery — so the real consumption charge lands near 25%.", PWC),
 "Payroll cycle": ("Monthly.", "Ghana Labour Act 2003"),
 "Minimum wage": ("21.77 GHS a day.", TE),
 "Working hours": ("8 hours a day and 40 hours a week, with 12 consecutive hours of daily rest and 48 hours of weekly rest.", "Ghana Labour Act 2003, s. 33"),
 "Overtime": ("Paid at a premium set by the contract; the Act requires a premium but not a fixed multiple.", "Ghana Labour Act 2003, s. 35"),
 "Social security": ("SSNIT: 13% employer and 5.5% employee, of which 13.5 points go to the first tier and 5 points to the second.", PWC),
 "Healthcare": ("The national health insurance levy funds the scheme; there is no separate employer premium.", PWC),
 "Retirement": ("Three tiers — the mandatory first and second inside the 18.5%, and a voluntary third-tier provident fund.", "National Pensions Act 2008"),
 "Paid time off": ("15 working days a year after twelve months of continuous service.", "Ghana Labour Act 2003, s. 20"),
 "Public holidays": ("13 paid public holidays.", WIKI),
 "Maternity leave": ("12 weeks at full pay, 14 for a multiple or complicated birth.", "Ghana Labour Act 2003, s. 57"),
 "Sick leave": ("No fixed statutory allowance. Absence on a medical certificate is not deducted from annual leave.", "Ghana Labour Act 2003, s. 24"),
 "Probation": ("Set by the contract; six months is the norm.", "Ghana Labour Act 2003"),
 "Notice period": ("A month for a monthly contract, two weeks for a contract of less than three years, a week for a weekly-paid worker after four weeks.", "Ghana Labour Act 2003, s. 17"),
 "Severance": ("Redundancy pay is negotiated with the worker or the union and, if they cannot agree, set by the Chief Labour Officer. One month per year of service is the common landing.", "Ghana Labour Act 2003, s. 65"),
}

N["Ecuador"] = {
 "Currency": ("US Dollar. Ecuador is dollarized and has no currency of its own.", "Central Bank of Ecuador"),
 "VAT": ("13%.", TE),
 "Payroll cycle": ("Monthly.", "Ecuador Labour Code"),
 "Minimum wage": ("482 USD a month — the Unified Basic Salary, which also sets the fourteenth-salary figure.", TE),
 "Working hours": ("8 hours a day and 40 hours a week.", "Ecuador Labour Code, art. 47"),
 "Overtime": ("50% premium up to 12 extra hours a week, 100% at night and on rest days.", "Ecuador Labour Code, art. 55"),
 "Social security": ("IESS: 12.15% employer and 9.45% employee on total remuneration, with no ceiling.", PWC),
 "Healthcare": ("IESS covers medical care; there is no separate employer premium.", PWC),
 "Retirement": ("IESS pension, plus a reserve fund of 8.33% of salary from the second year of service — paid monthly with the payroll or deposited with IESS at the employee's election.", "Ecuador Labour Code, art. 196"),
 "Paid time off": ("15 days a year including weekends after one year, with an extra day for each year past five, capped at 30.", "Ecuador Labour Code, art. 69"),
 "Public holidays": ("12 paid public holidays.", WIKI),
 "Maternity leave": ("12 weeks at full pay, split between IESS and the employer, and a nursing hour cut from the working day for a year afterward.", "Ecuador Labour Code, art. 152"),
 "Sick leave": ("The employer pays the first three days; IESS pays from the fourth.", "Ecuador Social Security Law"),
 "Probation": ("90 days, and the contract can be ended without indemnity inside it.", "Ecuador Labour Code, art. 15"),
 "Notice period": ("30 days' notice through the labour inspectorate for a resignation; an employer dismissal without cause pays indemnity rather than serving notice.", "Ecuador Labour Code, art. 184"),
 "Severance": ("Dismissal without cause pays a month's salary per year of service, floor of three months and cap of 25, plus 25% of the last salary for each year as a bonus indemnity.", "Ecuador Labour Code, art. 188"),
}

N["Slovakia"] = {
 "Currency": ("Euro (EUR).", "ISO 4217"),
 "VAT": ("23%.", TE),
 "Payroll cycle": ("Monthly, due by the end of the following calendar month at the latest.", "Slovak Labour Code, s. 129"),
 "Minimum wage": ("915 EUR a month, and the figure steps up by the job's difficulty level.", TE),
 "Working hours": ("40 hours a week.", "Slovak Labour Code, s. 85"),
 "Overtime": ("At least a 25% premium, 35% for hazardous work, capped at 150 hours a year without agreement.", "Slovak Labour Code, s. 121"),
 "Social security": ("Employer contributions run about 36.2% of gross across health, sickness, pension, disability, unemployment, accident, guarantee and reserve funds.", TE),
 "Healthcare": ("Compulsory health insurance: 11% employer, 4% employee.", "Slovak Health Insurance Act 580/2004"),
 "Retirement": ("Old-age and disability pension inside the social insurance package, plus a mandatory employer contribution to the second pillar.", "Slovak Social Insurance Act 461/2003"),
 "Paid time off": ("20 days a year, 25 for an employee aged 33 or over or caring for a child.", "Slovak Labour Code, s. 103"),
 "Public holidays": ("15 paid public holidays.", "Slovak Act on Holidays 241/1993"),
 "Maternity leave": ("34 weeks, paid by social insurance at 75% of the assessment base.", "Slovak Social Insurance Act 461/2003"),
 "Sick leave": ("The employer pays the first ten days; social insurance pays from day eleven.", "Slovak Act on Sickness Insurance"),
 "Probation": ("Three months, six for a senior role.", "Slovak Labour Code, s. 45"),
 "Notice period": ("One month under two years of service, two months from two to five years, three months beyond five.", "Slovak Labour Code, s. 62"),
 "Severance": ("One month's average earnings from two to five years of service, two months from five to ten, three months from ten to twenty, four months beyond twenty.", "Slovak Labour Code, s. 76"),
}

N["Slovenia"] = {
 "Currency": ("Euro (EUR).", "ISO 4217"),
 "VAT": ("22%.", TE),
 "Payroll cycle": ("Monthly, due no later than eighteen days after the period ends.", "Slovenian Employment Relationships Act (ZDR-1), art. 134"),
 "Minimum wage": ("1,482 EUR a month.", TE),
 "Working hours": ("40 hours a week.", "ZDR-1, art. 143"),
 "Overtime": ("Capped at 8 hours a week, 20 a month and 170 a year, with a premium set by collective agreement.", "ZDR-1, art. 143"),
 "Social security": ("Employer contributions are about 16.1% of gross; the employee carries a much larger 22.1%.", TE),
 "Healthcare": ("Compulsory health insurance sits inside the contribution split, and a separate compulsory health contribution applies per insured person.", "Slovenian Health Care and Health Insurance Act"),
 "Retirement": ("Pension and disability insurance inside the contribution package.", "Slovenian Pension and Disability Insurance Act"),
 "Paid time off": ("At least 20 working days a year, with extra days for age, seniority, disability and dependent children.", "ZDR-1, art. 159"),
 "Public holidays": ("13 to 15 paid public holidays.", "Slovenian Public Holidays Act"),
 "Maternity leave": ("105 days of maternity leave plus 260 days of parental leave, paid by the state.", "Slovenian Parental Protection and Family Benefits Act"),
 "Sick leave": ("The employer pays the first 20 working days of each absence; the health insurance institute pays after that.", "Slovenian Health Care and Health Insurance Act"),
 "Probation": ("Up to six months.", "ZDR-1, art. 125"),
 "Notice period": ("30 days for a business-reason dismissal above two years of service, growing two days per additional year to a 60-day cap; 15 days for fault; 7 days on a failed probation.", "ZDR-1, art. 94"),
 "Severance": ("A fifth of average monthly pay per year of service up to ten years, a quarter from ten to twenty, a third beyond twenty, capped at ten months' pay.", "ZDR-1, art. 108"),
}

N["Croatia"] = {
 "Currency": ("Euro (EUR). Croatia left the kuna in 2023.", "ISO 4217"),
 "VAT": ("25%.", TE),
 "Payroll cycle": ("Monthly, due by the fifteenth of the following month.", "Croatian Labour Act, art. 92"),
 "Minimum wage": ("1,050 EUR a month gross.", TE),
 "Working hours": ("40 hours a week.", "Croatian Labour Act, art. 61"),
 "Overtime": ("Capped at 8 hours a week, 180 hours a year, 250 by collective agreement, with a premium set by that agreement.", "Croatian Labour Act, art. 65"),
 "Social security": ("The employer's charge is health insurance at 16.5% of gross. Pension — 20% across both pillars — is deducted from the employee, so the split looks unusual against most of Europe.", "Croatian Contributions Act"),
 "Healthcare": ("Compulsory health insurance, 16.5%, employer only.", "Croatian Contributions Act"),
 "Retirement": ("Two pillars totalling 20%, both withheld from the employee's gross.", "Croatian Pension Insurance Act"),
 "Paid time off": ("Four weeks a year, five for hazardous work, and any carry-over must be used by 30 June of the next year.", "Croatian Labour Act, art. 77"),
 "Public holidays": ("13 paid public holidays.", WIKI),
 "Maternity leave": ("Compulsory maternity leave to 70 days after the birth, then leave to the child's sixth month at full pay, then parental leave.", "Croatian Maternity and Parental Benefits Act"),
 "Sick leave": ("The employer pays the first 42 days of every sick absence at 70% of salary; the health insurance fund pays after that.", "Croatian Health Insurance Act"),
 "Probation": ("Up to six months.", "Croatian Labour Act, art. 53"),
 "Notice period": ("Two weeks to three months, by length of service.", "Croatian Labour Act, art. 122"),
 "Severance": ("A third of average monthly pay per year of service after two years, capped at six months' pay.", "Croatian Labour Act, art. 126"),
}

N["Estonia"] = {
 "Currency": ("Euro (EUR).", "ISO 4217"),
 "VAT": ("24%.", TE),
 "Payroll cycle": ("Monthly.", "Estonian Employment Contracts Act, §33"),
 "Minimum wage": ("946 EUR a month.", TE),
 "Working hours": ("40 hours a week.", "Estonian Employment Contracts Act, §43"),
 "Overtime": ("Paid at 1.5 times the rate or given as time off, and the average week including overtime cannot exceed 48 hours over four months.", "Estonian Employment Contracts Act, §44"),
 "Social security": ("Social tax of 33% on gross, employer only, plus 0.8% unemployment insurance — no cap.", PWC),
 "Healthcare": ("Health insurance is funded out of the 33% social tax; there is no separate premium.", PWC),
 "Retirement": ("The state pension sits inside the social tax; the funded second pillar is 2% employee and 4% out of the social tax.", "Estonian Funded Pensions Act"),
 "Paid time off": ("28 calendar days a year.", "Estonian Employment Contracts Act, §55"),
 "Public holidays": ("12 paid public holidays.", WIKI),
 "Maternity leave": ("140 days of maternity leave at 100% of average earnings, paid by the health insurance fund, then shared parental benefit.", "Estonian Family Benefits Act"),
 "Sick leave": ("The first day is unpaid, the employer pays days two to eight, and the health insurance fund pays from day nine at 70%.", "Estonian Health Insurance Act"),
 "Probation": ("Up to four months.", "Estonian Employment Contracts Act, §86"),
 "Notice period": ("15 to 90 calendar days by length of service; 15 days inside probation.", "Estonian Employment Contracts Act, §97"),
 "Severance": ("One month's average pay on redundancy, plus a further month from the unemployment fund at five to ten years of service and two further months beyond ten.", "Estonian Employment Contracts Act, §100"),
}

N["Latvia"] = {
 "Currency": ("Euro (EUR).", "ISO 4217"),
 "VAT": ("21%.", TE),
 "Payroll cycle": ("At least twice a month unless the employee agrees to monthly.", "Latvian Labour Law, s. 69"),
 "Minimum wage": ("780 EUR a month.", TE),
 "Working hours": ("40 hours a week.", "Latvian Labour Law, s. 131"),
 "Overtime": ("Paid at double the hourly rate, capped at 8 hours a week on average over four months.", "Latvian Labour Law, s. 68"),
 "Social security": ("Mandatory state social insurance at 23.59% employer and 10.5% employee.", TE),
 "Healthcare": ("Funded from the social insurance contribution; there is no separate employer premium.", "Latvian State Social Insurance Agency"),
 "Retirement": ("State pension plus a mandatory funded tier inside the social insurance contribution.", "Latvian State Funded Pension Law"),
 "Paid time off": ("Four calendar weeks a year, excluding public holidays.", "Latvian Labour Law, s. 149"),
 "Public holidays": ("12 paid public holidays.", WIKI),
 "Maternity leave": ("112 days paid at 80% by the state, extendable to 140 for complications or an early registration.", "Latvian Law on Maternity and Sickness Insurance"),
 "Sick leave": ("The first day is unpaid; the employer pays days two and three at 75% and days four to ten at 80%; the state pays from day eleven.", "Latvian Law on Maternity and Sickness Insurance"),
 "Probation": ("Up to three months.", "Latvian Labour Law, s. 46"),
 "Notice period": ("One month as standard, two months once the employee has more than five years of service; three days inside probation.", "Latvian Labour Law, s. 103"),
 "Severance": ("One month's average earnings under five years of service, two months from five to ten, three months from ten to twenty, four months beyond twenty.", "Latvian Labour Law, s. 112"),
}

N["Lithuania"] = {
 "Currency": ("Euro (EUR).", "ISO 4217"),
 "VAT": ("21%.", TE),
 "Payroll cycle": ("Twice a month unless the employee asks in writing for monthly.", "Lithuanian Labour Code, art. 146"),
 "Minimum wage": ("1,153 EUR a month.", TE),
 "Working hours": ("40 hours a week.", "Lithuanian Labour Code, art. 112"),
 "Overtime": ("At least a 50% premium, 100% at night or on a rest day, capped at 8 hours a week.", "Lithuanian Labour Code, art. 144"),
 "Social security": ("Employer Sodra is only 1.77% — 1.45% social insurance, 0.16% long-term employment fund, 0.16% guarantee fund. The weight sits on the employee at 19.5%, because Lithuania moved the contributions across and grossed salaries up to match.", "Lithuanian State Social Insurance Fund (Sodra) rate schedule"),
 "Healthcare": ("Compulsory health insurance is inside the employee's 19.5%, not a separate employer premium.", "Sodra rate schedule"),
 "Retirement": ("State pension inside the social insurance package, plus a voluntary funded pillar.", "Lithuanian Law on Pension Accumulation"),
 "Paid time off": ("20 working days a year on a five-day week, plus three extra days after ten years with the same employer and one more every five years after that.", "Lithuanian Labour Code, art. 126"),
 "Public holidays": ("14 paid public holidays.", WIKI),
 "Maternity leave": ("126 calendar days paid by Sodra, then parental leave to the child's second birthday.", "Lithuanian Law on Sickness and Maternity Social Insurance"),
 "Sick leave": ("The employer pays the first two days at between 62.06% and 100%; Sodra pays from day three.", "Lithuanian Law on Sickness and Maternity Social Insurance"),
 "Probation": ("Up to three months.", "Lithuanian Labour Code, art. 36"),
 "Notice period": ("One month as standard, two months where the employee has under a year of service, and doubled or tripled for protected groups.", "Lithuanian Labour Code, art. 57"),
 "Severance": ("Half a month's average pay under one year of service, two months' pay from one to twenty years, and a further long-service payment from the guarantee fund beyond that.", "Lithuanian Labour Code, art. 57"),
}

N["Cyprus"] = {
 "Currency": ("Euro (EUR).", "ISO 4217"),
 "VAT": ("19%.", TE),
 "Payroll cycle": ("Monthly.", "Cyprus Protection of Wages Law"),
 "Minimum wage": ("A national minimum wage applies to most employees, set by ministerial decree and reviewed annually.", "Cyprus Ministry of Labour, national minimum wage decree"),
 "Working hours": ("48 hours a week including overtime, averaged over four months.", "Cyprus Organisation of Working Time Law"),
 "Overtime": ("Set by collective agreement rather than a single statutory premium.", "Cyprus Ministry of Labour guidance"),
 "Social security": ("Employer total is about 15.4%: 8.8% social insurance capped at 68,904 EUR of annual earnings, 2.9% national health, 2.0% social cohesion with no cap, 1.2% redundancy fund and 0.5% training fund.", "Cyprus Social Insurance Services 2026 rate schedule"),
 "Healthcare": ("The national health system (GESY) charge is 2.9% employer and 2.65% employee, capped at 180,000 EUR.", "Cyprus Social Insurance Services 2026 rate schedule"),
 "Retirement": ("Pension sits inside the 8.8% social insurance contribution; occupational provident funds are common but not compulsory.", "Cyprus Social Insurance Services"),
 "Paid time off": ("20 working days a year on a five-day week, 24 on a six-day week.", "Cyprus Annual Holidays with Pay Law"),
 "Public holidays": ("14 paid public holidays.", WIKI),
 "Maternity leave": ("18 weeks for a first child, longer for subsequent children and multiple births, paid by the social insurance fund.", "Cyprus Maternity Protection Law"),
 "Sick leave": ("Sickness benefit is paid by the social insurance fund from the fourth day; there is no statutory employer top-up.", "Cyprus Social Insurance Services"),
 "Probation": ("Six months as standard, extendable to two years by written agreement.", "Cyprus Termination of Employment Law"),
 "Notice period": ("One week at 26 to 51 weeks of service, rising in steps to eight weeks beyond 312 weeks.", "Cyprus Termination of Employment Law"),
 "Severance": ("Redundancy pay comes out of the state redundancy fund the employer has funded at 1.2%, at two weeks' pay per year of service for the first four years and rising by band after that.", "Cyprus Termination of Employment Law"),
}

N["Malta"] = {
 "Currency": ("Euro (EUR).", "ISO 4217"),
 "VAT": ("18%.", TE),
 "Payroll cycle": ("Monthly, at intervals no longer than four weeks.", "Malta Employment and Industrial Relations Act"),
 "Minimum wage": ("994 EUR a month.", TE),
 "Working hours": ("40 hours a week is the norm, 48 the ceiling averaged over 17 weeks.", "Malta Organisation of Working Time Regulations"),
 "Overtime": ("Paid at one and a half times the normal rate above the weekly norm.", "Malta Overtime Regulations"),
 "Social security": ("10% employer and 10% employee, subject to a weekly maximum — a flat 51.60 EUR a week each once the salary passes the threshold.", "Malta Social Security Act"),
 "Healthcare": ("Funded from social security; no separate employer premium.", "Malta Social Security Act"),
 "Retirement": ("State pension inside the social security contribution.", "Malta Social Security Act"),
 "Paid time off": ("At least 224 hours a year — 28 days on an eight-hour day — with the entitlement adjusted each year for public holidays falling on a weekend.", "Malta Annual Leave National Standard Order"),
 "Public holidays": ("14 paid public holidays.", WIKI),
 "Maternity leave": ("18 weeks, the first 14 paid by the employer and the last four by social security.", "Malta Protection of Maternity Regulations"),
 "Sick leave": ("Set by the sector's wage regulation order; the common entitlement is around two weeks at full pay and two more at reduced pay.", "Malta wage regulation orders"),
 "Probation": ("Six months as standard, up to twelve for a senior role.", "Malta Probation Period Regulations"),
 "Notice period": ("One week under a month of service, rising in steps to twelve weeks past ten years.", "Malta Employment and Industrial Relations Act, art. 36"),
 "Severance": ("No statutory redundancy pay. A redundant employee has the right to be reinstated if the post is filled again within twelve months.", "Malta Employment and Industrial Relations Act, art. 36"),
}

N["Luxembourg"] = {
 "Currency": ("Euro (EUR).", "ISO 4217"),
 "VAT": ("17%.", TE),
 "Payroll cycle": ("Monthly.", "Luxembourg Labour Code"),
 "Minimum wage": ("2,771 EUR a month for an unskilled adult, and about 20% higher for a qualified employee — a two-level statutory minimum.", TE),
 "Working hours": ("8 hours a day and 40 hours a week.", "Luxembourg Labour Code, art. L.211-5"),
 "Overtime": ("A 40% premium, usually taken as compensatory time at 1.5 hours off per hour worked.", "Luxembourg Labour Code, art. L.211-27"),
 "Social security": ("Employer contributions run roughly 12% to 15% of gross across health, pension, accident and the employers' mutual insurance scheme.", "Luxembourg Joint Social Security Centre (CCSS) rate schedule"),
 "Healthcare": ("Compulsory sickness insurance inside the contribution split; the employers' mutual scheme reimburses most of the employer's sick pay.", "CCSS rate schedule"),
 "Retirement": ("State pension at 8% employer and 8% employee inside the package.", "CCSS rate schedule"),
 "Paid time off": ("26 working days a year, earned after three months with the employer.", "Luxembourg Labour Code, art. L.233-4"),
 "Public holidays": ("11 paid public holidays.", WIKI),
 "Maternity leave": ("20 weeks paid by the health fund, with an eight-week post-birth block that cannot be waived.", "Luxembourg Labour Code, art. L.332-1"),
 "Sick leave": ("The employer pays full salary to the end of the month in which the 77th day of sickness falls, then the health fund takes over — and the employer recovers most of that from the mutual scheme.", "Luxembourg Labour Code, art. L.121-6"),
 "Probation": ("Two weeks to six months, and twelve months for an employee above a set salary level.", "Luxembourg Labour Code, art. L.121-5"),
 "Notice period": ("Two months under five years of service, four months from five to ten, six months beyond ten — and doubled where the employer initiates.", "Luxembourg Labour Code, art. L.124-1"),
 "Severance": ("Owed from five years of service: one month's pay at five to ten years, two at ten to fifteen, three at fifteen to twenty, six at twenty to twenty-five, nine at twenty-five to thirty, twelve beyond thirty.", "Luxembourg Labour Code, art. L.124-7"),
}

N["Iceland"] = {
 "Currency": ("Icelandic Krona (ISK).", "ISO 4217"),
 "VAT": ("24% standard, 11% reduced.", TE),
 "Payroll cycle": ("Monthly.", "Icelandic Act on Wages and Salaries"),
 "Minimum wage": ("No statutory national minimum. Pay floors come from sectoral collective agreements, and those agreements bind every employer in the sector whether or not the employee is a union member.", "Icelandic Act on Trade Unions and Industrial Disputes"),
 "Working hours": ("40 hours a week under law; most collective agreements have cut the working week to 36 or 37 hours.", "Icelandic Act on Working Environment"),
 "Overtime": ("Premium set by collective agreement, commonly 1.0385% of monthly pay per hour.", "Icelandic collective agreements"),
 "Social security": ("Social security tax of about 6.35% on gross.", TE),
 "Healthcare": ("Funded by the social security tax; no separate employer premium.", "Iceland Directorate of Health"),
 "Retirement": ("Pension is compulsory and expensive: at least 11.5% employer on top of the employee's 4%, and union and rehabilitation fund contributions ride alongside it.", "Icelandic Act on Mandatory Pension Insurance"),
 "Paid time off": ("24 working days a year under the Act; collective agreements commonly push it to 30 with seniority.", "Icelandic Annual Holidays Act"),
 "Public holidays": ("12 to 13 paid public holidays.", WIKI),
 "Maternity leave": ("12 months of parental leave shared between the parents, with six months reserved to each, paid at 80% by the Birth Leave Fund.", "Icelandic Act on Maternity/Paternity Leave"),
 "Sick leave": ("The employer pays the first two days of every month of service in the first year, rising sharply with seniority under the collective agreement; union sick funds pick up the rest.", "Icelandic collective agreements"),
 "Probation": ("Three months is the common term under collective agreements.", "Icelandic collective agreements"),
 "Notice period": ("One month under five years of service, two months from five to ten, three months beyond ten.", "Icelandic collective agreements"),
 "Severance": ("No statutory severance. The notice period, paid in full, is the exit cost.", "Icelandic Act on Working Environment"),
}

N["Qatar"] = {
 "Currency": ("Qatari Riyal (QAR), pegged to the US dollar.", "ISO 4217"),
 "VAT": ("None currently in force.", PWC),
 "Payroll cycle": ("Monthly, and wages must be paid through the Wage Protection System within seven days of the period ending.", "Qatar Labour Law and WPS regulations"),
 "Minimum wage": ("1,000 QAR a month in basic pay, plus mandated food and accommodation allowances where the employer does not provide them.", TE),
 "Working hours": ("8 hours a day and 48 hours a week, dropping to 6 and 36 during Ramadan.", "Qatar Labour Law, art. 73"),
 "Overtime": ("125% of the hourly rate, 150% at night, and a rest-day hour is paid at 150% plus a day off.", "Qatar Labour Law, art. 74"),
 "Social security": ("No social insurance for expatriates. Qatari nationals are covered by a separate state scheme.", "Qatar Social Insurance Law"),
 "Healthcare": ("Employers must provide health insurance for expatriate employees, and a residence permit will not issue without it.", "Qatar Health Services Law 22 of 2021"),
 "Retirement": ("No pension for expatriates. The end-of-service gratuity is the whole retirement provision.", "Qatar Labour Law"),
 "Paid time off": ("Three weeks a year under five years of service, four weeks beyond five.", "Qatar Labour Law, art. 79"),
 "Public holidays": ("The two Eids, National Day and National Sports Day, with the Eid dates moving on the lunar calendar.", "Qatar Labour Law, art. 75"),
 "Maternity leave": ("50 days at full pay for an employee with a year of service, at least 35 of them after the birth.", "Qatar Labour Law, art. 96"),
 "Sick leave": ("Two weeks at full pay, four at half pay, then unpaid to a twelve-week total.", "Qatar Labour Law, art. 82"),
 "Probation": ("Up to six months.", "Qatar Labour Law, art. 39"),
 "Notice period": ("One month up to two years of service, two months beyond.", "Qatar Labour Law, art. 49"),
 "Severance": ("End-of-service gratuity at three weeks' pay per year for one to five years, four weeks for five to ten, five weeks for ten to twenty, six weeks beyond twenty.", "Qatar Labour Law, art. 54"),
}

N["Kuwait"] = {
 "Currency": ("Kuwaiti Dinar (KWD).", "ISO 4217"),
 "VAT": ("None currently in force.", PWC),
 "Payroll cycle": ("Monthly, through the Wage Protection System.", "Kuwait Labour Law 6 of 2010"),
 "Minimum wage": ("75 KWD a month in the private sector.", "Kuwait Ministry of Social Affairs and Labour decree"),
 "Working hours": ("8 hours a day and 48 hours a week, dropping to 36 during Ramadan.", "Kuwait Labour Law, art. 64"),
 "Overtime": ("125% of the rate on a working day, 150% on a rest day, 200% on a public holiday.", "Kuwait Labour Law, art. 66"),
 "Social security": ("PIFSS applies to Kuwaiti nationals only, at about 11.5% employer. An expatriate employee carries no social insurance charge at all.", "Kuwait PIFSS rate schedule"),
 "Healthcare": ("Employers pay an annual government health insurance fee for each expatriate employee, and private cover is common on top.", "Kuwait Ministry of Health regulations"),
 "Retirement": ("No pension for expatriates. The end-of-service indemnity stands in for it.", "Kuwait Labour Law"),
 "Paid time off": ("30 working days a year.", "Kuwait Labour Law, art. 70"),
 "Public holidays": ("13 paid public holidays.", WIKI),
 "Maternity leave": ("70 days at full pay, plus up to four months of unpaid leave after it.", "Kuwait Labour Law, art. 24"),
 "Sick leave": ("Six paid bands over 75 days a year, stepping down from full pay to unpaid.", "Kuwait Labour Law, art. 69"),
 "Probation": ("Up to 100 working days.", "Kuwait Labour Law, art. 30"),
 "Notice period": ("Three months for a monthly-paid worker, one month for everyone else.", "Kuwait Labour Law, art. 44"),
 "Severance": ("End-of-service indemnity at 15 days' pay per year for the first five years and a month's pay per year after that, capped at one and a half years' pay.", "Kuwait Labour Law, art. 51"),
}

N["Bahrain"] = {
 "Currency": ("Bahraini Dinar (BHD), pegged to the US dollar.", "ISO 4217"),
 "VAT": ("10%.", TE),
 "Payroll cycle": ("Monthly, through the Wage Protection System.", "Bahrain Labour Law 36 of 2012"),
 "Minimum wage": ("No statutory private-sector minimum for expatriates; a public-sector floor applies to Bahraini nationals.", "Bahrain Ministry of Labour"),
 "Working hours": ("8 hours a day and 48 hours a week, dropping to 6 hours a day during Ramadan for Muslim employees.", "Bahrain Labour Law, art. 51"),
 "Overtime": ("125% by day, 150% by night, and 150% plus a compensatory day for rest-day work.", "Bahrain Labour Law, art. 53"),
 "Social security": ("SIO splits by nationality: 12% employer for a Bahraini national, 3% employer for an expatriate covering work injury only. A monthly labour market authority fee applies per expatriate on top.", "Bahrain Social Insurance Organisation rate schedule"),
 "Healthcare": ("Employers must provide health cover for expatriate employees; a state health insurance scheme is being phased in.", "Bahrain Health Insurance Law 23 of 2018"),
 "Retirement": ("The SIO pension branch covers Bahrainis only. An expatriate accrues leaving indemnity instead.", "Bahrain Social Insurance Law"),
 "Paid time off": ("30 days a year, accruing at 2.5 days a month.", "Bahrain Labour Law, art. 58"),
 "Public holidays": ("14 paid public holidays.", WIKI),
 "Maternity leave": ("60 days paid and a further 15 unpaid, plus paid nursing hours for a year afterward.", "Bahrain Labour Law, art. 32"),
 "Sick leave": ("55 days a year: 15 at full pay, 20 at half pay, 20 unpaid.", "Bahrain Labour Law, art. 65"),
 "Probation": ("Three months, extendable to six for a role requiring it.", "Bahrain Labour Law, art. 21"),
 "Notice period": ("30 days as a minimum.", "Bahrain Labour Law, art. 99"),
 "Severance": ("Leaving indemnity for an employee outside social insurance: half a month's wage per year for the first three years, a full month per year after that.", "Bahrain Labour Law, art. 116"),
}

N["Oman"] = {
 "Currency": ("Omani Rial (OMR), pegged to the US dollar.", "ISO 4217"),
 "VAT": ("5%.", TE),
 "Payroll cycle": ("Monthly, through the Wage Protection System.", "Oman Labour Law RD 53/2023"),
 "Minimum wage": ("325 OMR a month, and the floor applies to Omani nationals.", TE),
 "Working hours": ("8 hours a day and 40 hours a week under the 2023 law, cut from 45.", "Oman Labour Law RD 53/2023"),
 "Overtime": ("125% by day and 150% by night, or compensatory time by agreement.", "Oman Labour Law RD 53/2023"),
 "Social security": ("Omani nationals are covered by the Social Protection Fund. For expatriates the 2023 Social Protection Law introduced a mandatory savings scheme funded by a monthly contribution of around 9% of salary.", "Oman Social Protection Law RD 52/2023"),
 "Healthcare": ("Employers must provide health insurance for their employees under the Dhamani scheme.", "Oman Capital Market Authority, Dhamani regulations"),
 "Retirement": ("Pension for Omanis through the Social Protection Fund; for expatriates the savings scheme and the end-of-service gratuity.", "Oman Social Protection Law RD 52/2023"),
 "Paid time off": ("30 days a year after six months of service, and up to 30 days may be carried forward.", "Oman Labour Law RD 53/2023"),
 "Public holidays": ("Around 9 to 11 paid public holidays.", WIKI),
 "Maternity leave": ("98 days at full pay under the 2023 law, up from 50.", "Oman Labour Law RD 53/2023"),
 "Sick leave": ("182 days a year on a descending pay scale, up from 70 days under the old law.", "Oman Labour Law RD 53/2023"),
 "Probation": ("Three months for a monthly-paid employee.", "Oman Labour Law RD 53/2023"),
 "Notice period": ("30 days as a minimum on an indefinite contract.", "Oman Labour Law RD 53/2023"),
 "Severance": ("End-of-service gratuity for an expatriate is now a full month's basic salary for every year of service from the first year, replacing the old 15-day first-three-years formula. Service straddling the change is calculated in two parts.", "Oman Labour Law RD 53/2023; Oman Ministry of Labour clarification"),
}

N["Jordan"] = {
 "Currency": ("Jordanian Dinar (JOD), pegged to the US dollar.", "ISO 4217"),
 "VAT": ("16%.", TE),
 "Payroll cycle": ("Monthly.", "Jordan Labour Law 8 of 1996"),
 "Minimum wage": ("290 JOD a month.", TE),
 "Working hours": ("48 hours a week, and 8 hours a day is the norm.", "Jordan Labour Law, art. 56"),
 "Overtime": ("125% of the rate on a working day, 150% on a rest day or public holiday.", "Jordan Labour Law, art. 59"),
 "Social security": ("14.25% employer and 7.5% employee, covering old age, disability, death, maternity, unemployment and work injury.", "Jordan Social Security Corporation rate schedule"),
 "Healthcare": ("No mandatory employer medical scheme; private cover is a market benefit.", "Jordan Ministry of Health"),
 "Retirement": ("Old-age pension inside the social security contribution.", "Jordan Social Security Law"),
 "Paid time off": ("14 days a year, rising to 21 after five continuous years with the same employer.", "Jordan Labour Law, art. 61"),
 "Public holidays": ("10 to 14 paid public holidays, several of them lunar.", WIKI),
 "Maternity leave": ("90 days at full pay, funded by the social security maternity branch the employer contributes to.", "Jordan Labour Law (2024 amendment)"),
 "Sick leave": ("14 days a year at full pay, extendable to 14 more on hospital confirmation.", "Jordan Labour Law, art. 65"),
 "Probation": ("Up to three months.", "Jordan Labour Law, art. 35"),
 "Notice period": ("One month in writing, from either side.", "Jordan Labour Law, art. 23"),
 "Severance": ("Half a month's salary per year of service, with a two-month floor, plus 30 days' pay where no notice was given.", "Jordan Labour Law, art. 32"),
}

N["Bahamas"] = {
 "Currency": ("Bahamian Dollar (BSD), pegged one-to-one with the US dollar.", "ISO 4217"),
 "VAT": ("10%.", TE),
 "Payroll cycle": ("Weekly, fortnightly or monthly, and the wage period cannot exceed a month.", "Bahamas Employment Act 2001"),
 "Minimum wage": ("260 BSD a week — 5.25 an hour.", "Bahamas Ministry of Labour, minimum wage order"),
 "Working hours": ("40 hours a week over five days.", "Bahamas Employment Act 2001, s. 12"),
 "Overtime": ("Time and a half above 40 hours, double time on a public holiday or rest day.", "Bahamas Employment Act 2001, s. 13"),
 "Social security": ("National Insurance at 6.65% employer and 4.65% employee, on insurable wages up to a weekly ceiling.", "Bahamas National Insurance Board rate schedule"),
 "Healthcare": ("No mandatory employer plan under the Employment Act; the National Health Insurance scheme provides a primary-care benefit.", "Bahamas National Health Insurance Authority"),
 "Retirement": ("Retirement benefit through National Insurance; occupational plans are voluntary.", "Bahamas National Insurance Act"),
 "Paid time off": ("Two weeks a year, rising to three weeks after seven years of service.", "Bahamas Employment Act 2001, s. 17"),
 "Public holidays": ("10 to 11 paid public holidays.", WIKI),
 "Maternity leave": ("12 weeks, starting at least a week before the due date and running at least eight weeks after the birth.", "Bahamas Employment Act 2001, s. 20"),
 "Sick leave": ("One week a year at full pay.", "Bahamas Employment Act 2001, s. 18"),
 "Probation": ("Set by contract; six months is the norm.", "Bahamas Employment Act 2001"),
 "Notice period": ("A week for an hourly-paid employee, two weeks for a monthly-paid one, a month for a supervisor or manager.", "Bahamas Employment Act 2001, s. 29"),
 "Severance": ("Two weeks' pay per year of service for a non-supervisory employee, capped at 24 weeks; a month per year for a supervisor or manager, capped at 48 weeks.", "Bahamas Employment Act 2001, s. 29"),
}

N["Trinidad and Tobago"] = {
 "Currency": ("Trinidad and Tobago Dollar (TTD).", "ISO 4217"),
 "VAT": ("12.5%.", TE),
 "Payroll cycle": ("Fortnightly or monthly.", "Trinidad and Tobago Minimum Wages Act"),
 "Minimum wage": ("20.50 TTD an hour.", "Trinidad and Tobago Minimum Wages Order"),
 "Working hours": ("8 hours a day and 40 hours a week.", "Trinidad and Tobago Minimum Wages Act"),
 "Overtime": ("Time and a half for the first four extra hours, double time after that, and double time on a public holiday.", "Trinidad and Tobago Minimum Wages Act"),
 "Social security": ("National Insurance is charged in weekly earnings classes rather than as a percentage: the employer pays two thirds of the class contribution and the employee a third, on insurable earnings up to a weekly ceiling.", "Trinidad and Tobago National Insurance Board class schedule"),
 "Healthcare": ("No mandatory employer health plan; the public system carries it.", "Trinidad and Tobago Ministry of Health"),
 "Retirement": ("Retirement benefit through National Insurance; occupational pensions are voluntary.", "Trinidad and Tobago National Insurance Act"),
 "Paid time off": ("Two weeks a year after twelve months of service.", "Trinidad and Tobago Minimum Wages Act"),
 "Public holidays": ("14 paid public holidays.", "Trinidad and Tobago Public Holidays and Festivals Act"),
 "Maternity leave": ("14 weeks — one month at full pay and two months at half pay from the employer, with the National Insurance maternity grant alongside.", "Trinidad and Tobago Maternity Protection Act"),
 "Sick leave": ("14 days a year for a worker covered by the Minimum Wages Act.", "Trinidad and Tobago Minimum Wages Act"),
 "Probation": ("Set by contract; three months is the norm.", "Trinidad and Tobago Industrial Relations Act"),
 "Notice period": ("Set by contract, with 45 days' written notice mandatory before a retrenchment.", "Trinidad and Tobago Retrenchment and Severance Benefits Act"),
 "Severance": ("Retrenchment pay after one year of service: two weeks' pay per year for the first four years and three weeks per year after that, on 45 days' formal notice to the employee and the Minister.", "Trinidad and Tobago Retrenchment and Severance Benefits Act"),
}

N["Bermuda"] = {
 "Currency": ("Bermudian Dollar (BMD), pegged one-to-one with the US dollar.", "ISO 4217"),
 "VAT": ("None. Bermuda has no VAT or sales tax; customs duty carries the load instead.", PWC),
 "Payroll cycle": ("Monthly or fortnightly.", "Bermuda Employment Act 2000"),
 "Minimum wage": ("A statutory minimum hourly wage applies under the Employment (Minimum Hourly Wage) Order.", "Bermuda Ministry of Economy and Labour"),
 "Working hours": ("Set by contract, with a rest period of at least 24 consecutive hours a week.", "Bermuda Employment Act 2000"),
 "Overtime": ("No statutory premium; the contract governs.", "Bermuda Employment Act 2000"),
 "Social security": ("Payroll tax is the main employer charge — 10.25% of remuneration for an exempted undertaking, with different bands by payroll size and sector. Social insurance is a flat weekly amount per employee, split evenly with the employee.", PWC),
 "Healthcare": ("Health insurance is compulsory. The employer must provide at least the Standard Health Benefit for every employee and any non-employed spouse, is liable for the whole premium, and may recover up to half from the employee.", "Bermuda Health Insurance Act 1970"),
 "Retirement": ("A registered occupational pension is compulsory for Bermudian employees and their spouses aged 23 to 65 with 720 hours of service in a year, at 5% employer and 5% employee.", "Bermuda National Pension Scheme (Occupational Pensions) Act 1998"),
 "Paid time off": ("Two weeks after the first year of continuous employment; there is no statutory accrual above that.", "Bermuda Employment Act 2000, s. 17"),
 "Public holidays": ("10 paid public holidays.", "Bermuda Public Holidays Act 1947"),
 "Maternity leave": ("13 weeks, eight of them paid for an employee with a year of service.", "Bermuda Employment Act 2000, s. 20"),
 "Sick leave": ("8 paid days a year after a year of continuous employment.", "Bermuda Employment Act 2000, s. 19"),
 "Probation": ("Set by contract, commonly three to six months.", "Bermuda Employment Act 2000"),
 "Notice period": ("A week for weekly pay, two weeks for fortnightly, a month for monthly, and longer by contract.", "Bermuda Employment Act 2000, s. 20"),
 "Severance": ("Two weeks' wages per year of service on redundancy, capped at 26 weeks.", "Bermuda Employment Act 2000, s. 22"),
}

N["Cayman Islands"] = {
 "Currency": ("Cayman Islands Dollar (KYD), pegged to the US dollar.", "ISO 4217"),
 "VAT": ("None. There is no VAT, sales tax or income tax; import duty carries the revenue.", "Cayman Islands Government"),
 "Payroll cycle": ("Monthly or fortnightly, and wages must be paid at least monthly.", "Cayman Islands Labour Act (2021 Revision)"),
 "Minimum wage": ("6.00 KYD an hour, with a lower floor for tipped service staff.", "Cayman Islands Labour (Minimum Wage) Order"),
 "Working hours": ("45 hours a week over five days, or 45 hours over a longer week in some sectors.", "Cayman Islands Labour Act, s. 22"),
 "Overtime": ("Time and a half above the standard week.", "Cayman Islands Labour Act, s. 24"),
 "Social security": ("No social security or payroll tax. The mandatory charges are pension and health insurance, both paid to private providers.", "Cayman Islands Government"),
 "Healthcare": ("Compulsory. The employer must provide at least the Standard Health Insurance Contract from the first day of employment and pay at least half the premium.", "Cayman Islands Health Insurance Law"),
 "Retirement": ("A registered pension plan is compulsory at 5% employer and 5% employee of pensionable earnings.", "Cayman Islands National Pensions Act"),
 "Paid time off": ("Two weeks a year, rising to three weeks after four years and four weeks after ten.", "Cayman Islands Labour Act, s. 32"),
 "Public holidays": ("11 paid public holidays.", "Cayman Islands Public Holidays Act"),
 "Maternity leave": ("14 weeks, the first four at full pay and the next four at half pay from the employer.", "Cayman Islands Labour Act, s. 42"),
 "Sick leave": ("10 paid days a year after the first three months of employment.", "Cayman Islands Labour Act, s. 38"),
 "Probation": ("Up to three months, extendable once in writing to six.", "Cayman Islands Labour Act, s. 11"),
 "Notice period": ("A week after a month of service, two weeks after a year, a month after five years.", "Cayman Islands Labour Act, s. 60"),
 "Severance": ("A week's pay per year of continuous service on redundancy after twelve months.", "Cayman Islands Labour Act, s. 62"),
}

N["Kazakstan"] = {
 "Currency": ("Kazakhstani Tenge (KZT).", "ISO 4217"),
 "VAT": ("16%.", TE),
 "Payroll cycle": ("Monthly, due no later than the tenth of the following month.", "Kazakhstan Labour Code, art. 113"),
 "Minimum wage": ("85,000 KZT a month.", TE),
 "Working hours": ("40 hours a week.", "Kazakhstan Labour Code, art. 68"),
 "Overtime": ("At least 1.5 times the rate, capped at 2 hours a day and 12 hours a month.", "Kazakhstan Labour Code, art. 108"),
 "Social security": ("Employer side: 9.5% social tax, 3.5% social insurance, 3% mandatory medical insurance, and 1.5% mandatory employer pension. The employee carries a further 10% pension and 2% medical.", "Kazakhstan Tax Code; State Social Insurance Fund schedules"),
 "Healthcare": ("Mandatory medical insurance at 3% employer and 2% employee, capped at ten times the minimum monthly wage.", "Kazakhstan Law on Compulsory Social Health Insurance"),
 "Retirement": ("10% employee pension contribution to the Unified Accumulative Pension Fund, plus a 1.5% mandatory employer pension contribution phased in from 2024.", "Kazakhstan Law on Pension Provision"),
 "Paid time off": ("24 calendar days a year.", "Kazakhstan Labour Code, art. 88"),
 "Public holidays": ("16 public holidays.", WIKI),
 "Maternity leave": ("126 calendar days — 70 before and 56 after the birth — with a lump-sum social insurance payment.", "Kazakhstan Labour Code, art. 99"),
 "Sick leave": ("Paid by the employer against a medical certificate, subject to a monthly cap tied to the monthly calculation index.", "Kazakhstan Labour Code, art. 133"),
 "Probation": ("Up to three months, six for a senior role.", "Kazakhstan Labour Code, art. 36"),
 "Notice period": ("One month for a redundancy or liquidation.", "Kazakhstan Labour Code, art. 53"),
 "Severance": ("One average monthly salary on redundancy or liquidation, and two on a liquidation in some cases.", "Kazakhstan Labour Code, art. 131"),
}

N["Georgia"] = {
 "Currency": ("Georgian Lari (GEL).", "ISO 4217"),
 "VAT": ("18%.", TE),
 "Payroll cycle": ("Monthly.", "Georgia Labour Code, art. 30"),
 "Minimum wage": ("The statutory minimum has not been revised since 1999 and is effectively symbolic; market pay sets the floor.", "Georgia Ministry of Economy"),
 "Working hours": ("40 hours a week, 48 in listed continuous-operation sectors.", "Georgia Labour Code, art. 24"),
 "Overtime": ("Paid at an increased hourly rate set by agreement, and overtime must be agreed.", "Georgia Labour Code, art. 25"),
 "Social security": ("There is no employer social security, unemployment or workers' compensation charge. The one mandatory contribution is the pension scheme: 2% employer, 2% employee, 2% state.", "Georgia Law on Funded Pensions"),
 "Healthcare": ("No employer health premium. The state universal health programme covers residents; private cover is a market benefit.", "Georgia Ministry of Health"),
 "Retirement": ("The funded pension scheme, mandatory for employees under 40 and optional above that age.", "Georgia Law on Funded Pensions"),
 "Paid time off": ("24 working days a year of paid leave, plus 15 unpaid days.", "Georgia Labour Code, art. 31"),
 "Public holidays": ("15 to 17 public holidays.", WIKI),
 "Maternity leave": ("183 calendar days of paid maternity leave — 200 for a complicated or multiple birth — with the state paying a capped benefit and any top-up left to the employer.", "Georgia Labour Code, art. 37"),
 "Sick leave": ("No separate statutory paid sick leave; absence runs against the leave entitlement or contract terms.", "Georgia Labour Code"),
 "Probation": ("Up to six months, on a separate written agreement, and it can be used only once with the same employee.", "Georgia Labour Code, art. 12"),
 "Notice period": ("30 calendar days' notice with one month's pay, or 3 days' notice with two months' pay.", "Georgia Labour Code, art. 48"),
 "Severance": ("At least one month's salary, payable within 30 days of termination.", "Georgia Labour Code, art. 48"),
}

N["Mauritius"] = {
 "Currency": ("Mauritian Rupee (MUR).", "ISO 4217"),
 "VAT": ("15%.", TE),
 "Payroll cycle": ("Monthly, due within the first week of the following month.", "Mauritius Workers' Rights Act 2019"),
 "Minimum wage": ("17,110 MUR a month, with a state-funded salary compensation added each January.", TE),
 "Working hours": ("45 hours a week, excluding breaks.", "Mauritius Workers' Rights Act 2019, s. 22"),
 "Overtime": ("One and a half times the rate on a normal day, double on a public holiday, and overtime must be agreed.", "Mauritius Workers' Rights Act 2019, s. 25"),
 "Social security": ("Employer side: 6% Contribution Sociale Généralisée for an employee above the salary threshold (3% below it), 2.5% National Savings Fund, and a 1.5% training levy.", "Mauritius Revenue Authority CSG and NSF schedules"),
 "Healthcare": ("No mandatory employer medical scheme; the public system is free at the point of use.", "Mauritius Ministry of Health"),
 "Retirement": ("The Portable Retirement Gratuity Fund is compulsory: a monthly employer contribution per worker, filed with the Revenue Authority, that follows the worker between employers rather than sitting on the employer's books.", "Mauritius Workers' Rights Act 2019; MRA PRGF Guide"),
 "Paid time off": ("22 working days a year — 20 annual and 2 additional — after twelve months of continuous service.", "Mauritius Workers' Rights Act 2019, s. 45"),
 "Public holidays": ("16 paid public holidays.", WIKI),
 "Maternity leave": ("14 weeks at full pay for an employee with twelve months of continuous service.", "Mauritius Workers' Rights Act 2019, s. 50"),
 "Sick leave": ("15 working days a year at full pay after twelve months of service, with unused days bankable.", "Mauritius Workers' Rights Act 2019, s. 46"),
 "Probation": ("Set by contract; the Act's protections attach from the first day either way.", "Mauritius Workers' Rights Act 2019"),
 "Notice period": ("At least 30 days.", "Mauritius Workers' Rights Act 2019, s. 66"),
 "Severance": ("Where a termination is found unjustified, severance runs at three months' remuneration per year of service.", "Mauritius Workers' Rights Act 2019, s. 70"),
}

assert len(N) == 35, len(N)
for c, d in N.items():
    missing = [k for k in ORDER if k not in d]
    assert not missing, (c, missing)
    extra = [k for k in d if k not in ORDER]
    assert not extra, (c, extra)

out = {}
for c, d in N.items():
    out[c] = [[k, d[k][0], "v", d[k][1]] for k in ORDER]

p = os.path.dirname(os.path.abspath(__file__))
with io.open(os.path.join(p, "public-source-countries.json"), "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=1)
print("countries", len(out), "bullets", sum(len(v) for v in out.values()))
