// The country wing's data — every country on the EOR pricing list, with the
// lead lines that say what is specific to THIS one and the sixteen points
// behind them. Generated by tools/country-sheet/build-app-countries.py from the
// parsed PrismHR guides, their corrections, and the countries written from
// public sources.
//
// Server-side only. The sheet is ~360KB; the Playbook hands the client a small
// index (name, alias, how many points are on file) and serves a country's card
// from /playbook/country when the operator names one. Arrival budgets are hard
// limits (click-depth law), so the depth travels on demand.

import sheet from "./countries.json";

export type Rung = "tape" | "filed" | "research" | "none";
export type Verdict = "ok" | "note" | "ask" | "no";

type CountryPoint = { label: string; value: string; source?: string };

export type CountryRow = {
  /** Country name as the pricing list spells it. */
  name: string;
  /** Alternate spellings an operator might type — "uk", "usa", "holland". */
  alias: string;
  /** How many of the sixteen points are written up. */
  points: number;
  /** What we can say the moment they name it. */
  verdict: Verdict;
  /** True when the country is on the EOR pricing list at all. */
  priced: boolean;
};

export type CountryCard = CountryRow & {
  /** The verdict in one sentence, and the rung it stands on. */
  verdictLine: string;
  verdictRung: Rung;
  /** What makes this country a project — read these first. */
  lead: string[];
  /** Currency, VAT, cycle, wage floor, hours, overtime, social security,
   *  healthcare, retirement, leave, holidays, maternity, sick, probation,
   *  notice, severance. */
  sixteen: CountryPoint[];
};

type RawPoint = [string, string] | [string, string, string, string];
type RawRow = {
  n: string;
  slug: string;
  alias: string;
  lead: string[];
  points: RawPoint[];
};
type RawSheet = {
  priced: number;
  fromGuide: number;
  fromPublicSources: number;
  written: number;
  bullets: number;
  leadLines: number;
  rows: RawRow[];
};

const raw = sheet as RawSheet;

/** What the wing's header says: how many are priced, how many are written up. */
export const COUNTRY_TALLY = { priced: raw.priced, written: raw.written };

// Countries we price but never promise blind. Authored, not generated — each
// line carries the rung it stands on (evidence or nothing).
const RISK: Record<string, [Verdict, string, Rung]> = {
  "puerto rico": [
    "note",
    "US soil, its own payroll jurisdiction. Runs on domestic Prism tech, not the global platform.",
    "tape",
  ],
  canada: ["note", "Our own payroll tech in country.", "tape"],
  ukraine: [
    "ask",
    "Active conflict. We price it. Confirm before you promise a start date.",
    "tape",
  ],
  belarus: ["ask", "Targeted sanctions. Ask before you promise.", "research"],
  myanmar: ["ask", "Targeted sanctions. Ask before you promise.", "research"],
  venezuela: ["ask", "Targeted sanctions. Ask before you promise.", "research"],
  yemen: ["ask", "Conflict. Ask before you promise.", "research"],
  libya: ["ask", "Conflict. Ask before you promise.", "research"],
  somalia: ["ask", "Conflict. Ask before you promise.", "research"],
  israel: [
    "note",
    "Priced. Confirm the region with the person before you promise a date.",
    "research",
  ],
};

// Named often enough on calls to need an answer, and not on our list.
const UNLISTED: Record<string, [Verdict, string, Rung]> = {
  russia: ["no", "Not on our list. Sanctioned.", "tape"],
  "north korea": ["no", "Not on our list. Sanctioned.", "research"],
  cuba: ["no", "Not on our list. Sanctioned.", "research"],
  iran: ["no", "Not on our list. Sanctioned.", "research"],
  syria: ["no", "Not on our list. Sanctioned.", "research"],
  afghanistan: ["no", "Not on our list.", "research"],
  sudan: ["no", "Not on our list.", "research"],
  "south sudan": ["no", "Not on our list.", "research"],
};

const YES: [string, Rung] = ["We operate there with our own entity in country.", "tape"];

function verdictFor(name: string): [Verdict, string, Rung] {
  const hit = RISK[name.toLowerCase()] ?? UNLISTED[name.toLowerCase()];
  return hit ?? ["ok", YES[0], YES[1]];
}

function titleCase(s: string): string {
  return s.replace(/(^|\s)\S/g, (c) => c.toUpperCase());
}

const byName = new Map(raw.rows.map((r) => [r.n.toLowerCase(), r]));

/** The whole list, small enough to arrive with the page: what the operator can
 *  type at, and what we can say before anything is fetched. */
export function countryIndex(): CountryRow[] {
  const rows: CountryRow[] = raw.rows.map((r) => {
    const [verdict] = verdictFor(r.n);
    return {
      name: r.n,
      alias: r.alias,
      points: r.points.length,
      verdict,
      priced: true,
    };
  });
  for (const key of Object.keys(UNLISTED)) {
    if (byName.has(key)) continue;
    rows.push({
      name: titleCase(key),
      alias: "",
      points: 0,
      verdict: UNLISTED[key][0],
      priced: false,
    });
  }
  return rows;
}

/** One country in full. Null when the name is neither priced nor one of the
 *  ones we get asked about and don't cover. */
export function countryCard(name: string): CountryCard | null {
  const key = name.trim().toLowerCase();
  const row = byName.get(key);
  const [verdict, verdictLine, verdictRung] = verdictFor(key);
  if (!row) {
    if (!UNLISTED[key]) return null;
    return {
      name: titleCase(key),
      alias: "",
      points: 0,
      verdict,
      priced: false,
      verdictLine,
      verdictRung,
      lead: [],
      sixteen: [],
    };
  }
  return {
    name: row.n,
    alias: row.alias,
    points: row.points.length,
    verdict,
    priced: true,
    verdictLine,
    verdictRung,
    lead: row.lead,
    sixteen: row.points.map((p) => ({
      label: p[0],
      value: p[1],
      source: p.length === 4 ? p[3] : undefined,
    })),
  };
}
