/**
 * Icon manifest — generated by tools/design-system/generate-icons.py
 * from the iconography mockup (spec 09 §3): 11 sacred nouns ·
 * 17 operator verbs · 11 system & wayfinding · 7 status = 46 glyphs.
 * DEFAULT_ACCENTS carries each glyph's rationed tick (09 §1.2);
 * glyphs absent from it are all-navy. Regenerate after a glyph
 * redraw; do not hand-edit.
 *
 * Bundling note: this registry imports all 46 glyphs, so <Icon>
 * carries the full set (~trivial at 46 small components on a desktop
 * product). Direct per-glyph imports stay tree-shakeable for the rare
 * consumer that wants one glyph without the registry.
 */
import type { FunctionComponent } from "preact";
import type { GlyphProps } from "./glyph";
import type { IconAccent } from "./glyph";
import { IcpGlyph } from "./glyphs/Icp";
import { FocusGlyph } from "./glyphs/Focus";
import { AccountGlyph } from "./glyphs/Account";
import { SignalGlyph } from "./glyphs/Signal";
import { MotionGlyph } from "./glyphs/Motion";
import { CallGlyph } from "./glyphs/Call";
import { DealGlyph } from "./glyphs/Deal";
import { ProofGlyph } from "./glyphs/Proof";
import { AdvisorGlyph } from "./glyphs/Advisor";
import { ReadinessGlyph } from "./glyphs/Readiness";
import { HandoffGlyph } from "./glyphs/Handoff";
import { SendGlyph } from "./glyphs/Send";
import { DraftGlyph } from "./glyphs/Draft";
import { CarryGlyph } from "./glyphs/Carry";
import { WriteUpGlyph } from "./glyphs/WriteUp";
import { AskGlyph } from "./glyphs/Ask";
import { PrepGlyph } from "./glyphs/Prep";
import { TightenGlyph } from "./glyphs/Tighten";
import { AddGlyph } from "./glyphs/Add";
import { DismissGlyph } from "./glyphs/Dismiss";
import { SkipGlyph } from "./glyphs/Skip";
import { FindGlyph } from "./glyphs/Find";
import { OpenGlyph } from "./glyphs/Open";
import { EditGlyph } from "./glyphs/Edit";
import { SaveGlyph } from "./glyphs/Save";
import { ExportGlyph } from "./glyphs/Export";
import { ImportGlyph } from "./glyphs/Import";
import { DeleteGlyph } from "./glyphs/Delete";
import { CtrlKGlyph } from "./glyphs/CtrlK";
import { WayfinderGlyph } from "./glyphs/Wayfinder";
import { BriefingGlyph } from "./glyphs/Briefing";
import { GaugeGlyph } from "./glyphs/Gauge";
import { SettingsGlyph } from "./glyphs/Settings";
import { BackGlyph } from "./glyphs/Back";
import { CloseGlyph } from "./glyphs/Close";
import { ExpandGlyph } from "./glyphs/Expand";
import { MoreGlyph } from "./glyphs/More";
import { ProposalGlyph } from "./glyphs/Proposal";
import { ObservationGlyph } from "./glyphs/Observation";
import { ReadyGlyph } from "./glyphs/Ready";
import { AttentionGlyph } from "./glyphs/Attention";
import { AtRiskGlyph } from "./glyphs/AtRisk";
import { ExecGlyph } from "./glyphs/Exec";
import { QuietGlyph } from "./glyphs/Quiet";
import { CompoundingGlyph } from "./glyphs/Compounding";
import { StillWeakGlyph } from "./glyphs/StillWeak";

export const ICON_NAMES = [
    "icp",
    "focus",
    "account",
    "signal",
    "motion",
    "call",
    "deal",
    "proof",
    "advisor",
    "readiness",
    "handoff",
    "send",
    "draft",
    "carry",
    "write-up",
    "ask",
    "prep",
    "tighten",
    "add",
    "dismiss",
    "skip",
    "find",
    "open",
    "edit",
    "save",
    "export",
    "import",
    "delete",
    "ctrl-k",
    "wayfinder",
    "briefing",
    "gauge",
    "settings",
    "back",
    "close",
    "expand",
    "more",
    "proposal",
    "observation",
    "ready",
    "attention",
    "at-risk",
    "exec",
    "quiet",
    "compounding",
    "still-weak",
] as const;

export type IconName = (typeof ICON_NAMES)[number];

export const GLYPHS: Readonly<Record<IconName, FunctionComponent<GlyphProps>>> = {
    "icp": IcpGlyph,
    "focus": FocusGlyph,
    "account": AccountGlyph,
    "signal": SignalGlyph,
    "motion": MotionGlyph,
    "call": CallGlyph,
    "deal": DealGlyph,
    "proof": ProofGlyph,
    "advisor": AdvisorGlyph,
    "readiness": ReadinessGlyph,
    "handoff": HandoffGlyph,
    "send": SendGlyph,
    "draft": DraftGlyph,
    "carry": CarryGlyph,
    "write-up": WriteUpGlyph,
    "ask": AskGlyph,
    "prep": PrepGlyph,
    "tighten": TightenGlyph,
    "add": AddGlyph,
    "dismiss": DismissGlyph,
    "skip": SkipGlyph,
    "find": FindGlyph,
    "open": OpenGlyph,
    "edit": EditGlyph,
    "save": SaveGlyph,
    "export": ExportGlyph,
    "import": ImportGlyph,
    "delete": DeleteGlyph,
    "ctrl-k": CtrlKGlyph,
    "wayfinder": WayfinderGlyph,
    "briefing": BriefingGlyph,
    "gauge": GaugeGlyph,
    "settings": SettingsGlyph,
    "back": BackGlyph,
    "close": CloseGlyph,
    "expand": ExpandGlyph,
    "more": MoreGlyph,
    "proposal": ProposalGlyph,
    "observation": ObservationGlyph,
    "ready": ReadyGlyph,
    "attention": AttentionGlyph,
    "at-risk": AtRiskGlyph,
    "exec": ExecGlyph,
    "quiet": QuietGlyph,
    "compounding": CompoundingGlyph,
    "still-weak": StillWeakGlyph,
};

export const DEFAULT_ACCENTS: Readonly<Partial<Record<IconName, IconAccent>>> = {
    "signal": "blue",
    "send": "orange",
    "carry": "orange",
    "wayfinder": "orange",
    "proposal": "orange",
    "ready": "green",
    "attention": "amber",
    "at-risk": "red",
    "compounding": "green",
};
